default: &default
  adapter: oracle_enhanced
  username: sas

development:
  <<: *default
  adapter: oracle_enhanced
  database: //211.110.141.206:1521/sas_prod
#  password: <%= ENV["MGM_WEB_DATABASE_PASSWORD"] %>
  password: Sas002918