default: &default
  adapter: oracle_enhanced
  username: sas

production:
  <<: *default
  adapter: oracle_enhanced
  database: //211.189.89.23:1521/sas_prod
#  password: <%= ENV["MGM_WEB_DATABASE_PASSWORD"] %>
  password: hLVY7GhZkaPNdnXm